### ISSUE TITLE
[TODO] Add Jest/React Testing Library tests

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#24]
A good app needs some tests. The one we have is the default for Jest/RTL that comes with Create React App 5.

Add a test folder and create some initial tests for the UI,etc.

**Comment by Sky-De** [comment]
@gbowne1 hi there, i would like to work on this, please assign this to me
Thanks

**Comment by gbowne1** [comment]
Ok @Sky-De will assign you

**Comment by Sky-De** [comment]
@gbowne1 thanks for assignment, for start i will add packages and initializing testing setup with one sample test, because it is lot of works testing all app at once , then I'll test components one by one , is it ok with you?

**Comment by gbowne1** [comment]
there are already testing packages installed.  

That is fine with me @Sky-De
