### ISSUE TITLE
[TODO][Bug] There is no UI item to close the drawer

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#33]
There is no close button to close the drawer 

Maybe add an X or a close button or some other element to close the drawer

**Comment by gbowne1** [comment]
There's also a small bug in the Theme switch in the top bar when the drawer is open, click on the theme switch and it will close the drawer (with the drawer menu open)

**Comment by caiomauro** [comment]
Found this on goodfirstissues.com, will take a look

**Comment by Babuprasanth27** [comment]
Hey, Shall I fix this issue?

**Comment by gbowne1** [comment]
@Babuprasanth27 Yes you can if you would like to.  thanks.

**Comment by Babuprasanth27** [comment]
@gbowne1 I've implemented the requested feature in the DrawerMenu component by adding a close button with the corresponding functionality. Before proceeding with the pull request, I wanted to confirm the preferred approach with you.
Would you prefer I submit the pull request for the DrawerMenu component alone, focusing solely on the changes made to address the issue? Alternatively, I can submit the pull request including all modifications currently present in my local machine.
Additionally, I've incorporated support for Windows by installing the "cross-env" package, ensuring compatibility across different operating systems.Please let me know your preference, and I'll proceed accordingly. Your clear guidance on this matter would be greatly appreciated.

**Comment by gbowne1** [comment]
@Babuprasanth27 I would prefer separate PRs for each item usually coupled to a issue, bug report, feature request, etc, etc.  

If there is no issue, bug report, feature request, etc for a given issue,  bug,  feature, please create one of those items and submit the PR under that. 

Thanks greatly

**Comment by Babuprasanth27** [comment]
@gbowne1 I have created the pull request as discussed. Please review it at your earliest convenience. If you need any modifications or additional changes, please let me know.

**Comment by gbowne1** [comment]
I've reviewed your PR @Babuprasanth27 and have added the other maintainers/ collaborators to the PR for review.

Thanks for the opportunity to review your PR and for your contribution.

**Comment by Babuprasanth27** [comment]
@gbowne1 Could you explain the bug or changes that I need to do?

**Comment by gbowne1** [comment]
@Babuprasanth27 I'm not sure where we were at with this. I haven't reviewed this in a bit.  The client/frontend needs work.

**Comment by Babuprasanth27** [comment]
@gbowne1  ok, let me see the client/frontend part..
