### ISSUE TITLE
[TODO] Add a ESLint & Prettier configuration

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#35]
The docs are here: https://eslint.org/docs/latest/use/configure/ and https://prettier.io/docs/en/configuration.html

I also wrote some notes for it:  https://github.com/gbowne1/ProgrammerNotes/blob/main/configure-eslint.md

Create a ESLint and Prettier configuration files .eslintrc.js  and .prettierrc

**Comment by jarmentor** [comment]
I'm going to do my best to resolve this one.

**Comment by gbowne1** [comment]
@jarmentor My concern is addressed here 

https://github.com/gbowne1/ProgrammerNotes/blob/main/configure-eslint.md#configurations

I hope I documented ESLint well enough to help with this.

We should also ship a quick-lint-js configuration too
