### ISSUE TITLE
[TODO] Add login/logout to the app 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#42]
The front end needs a login and logout 

I stuck in a login panel when the app loads fron the development server.

Clicking on Login doesn't currently work 

This is also a backend task but could be broken in to both tasks if necessary so that someone could do the frontend work and the backend server work separately.

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting to solve the issue if there is no one currenlty working on it , and i need some informatioins

**Comment by gbowne1** [comment]
@Amrani-Farouk-Hossam-Eddine 

There's no one working on it.

What information do you need?

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
I started working on the issue

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i'm done with the backend i need informataions about the frontedn
