### ISSUE TITLE
[Bug] Protected routes

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#48]
Currently you don't need to be logged in to be able to see other routes like /about etc one can just type in /about or some other routable URI after localhost:3000..

Protect the app by not allowing users to manually go to any other route without first asking the user to log in and authenticate and authorize themselves, perhaps even register.

This will improve security

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i'm interesting in working on this issue if no one is working on it currently

**Comment by gbowne1** [comment]
Ok @Amrani-Farouk-Hossam-Eddine 

I assigned you.
