### ISSUE TITLE
[Bug] Deprecated index.css properities causing Firefox issues

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#50]
**Describe the bug**

In the Firefox browser console you will see:

`Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.`

`Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.`

**Expected behavior**
These errors should not appear

**Desktop (please complete the following information):**
 - OS: Linux (and probably Windows)
 - Browser: Firefox
 - Version [any]

**Additional context**
The fix for this is easy.  Just fix the deprecated properities in the /src/client/src/index.css file

**Comment by gbowne1** [comment]
This issue was fixed in another repo I have here:

https://github.com/gbowne1/codebooker/pull/196/commits/dbe24ad1a3d359d074c0a3e7c98cd4aa2b063eb0

not sure if removing it really helps the issue out.

**Comment by jarmentor** [comment]
@gbowne1 - I've done a [little bit of research](https://github.com/google/fonts/issues/1170) on this. I think removal is the way to go

**Comment by gbowne1** [comment]
Alright fine enough for me @jarmentor
