### ISSUE TITLE
Add documentation on lint and Prettier 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#64]
Since we have new ESLint and Prettier configuration added we should add lint and Prettier requirements and documentation to the README.md and other documentation.

I would like to recommend that all new commit and PR cycles be finished with a run of Prettier and ESLint as well as tests. 

This will ensure that as our project grows it stays consistent and relatively free of lint and browser console errors.

**Comment by jarmentor** [comment]
Noting that [documentation has been started](https://github.com/gbowne1/TwitchBot/wiki/Linting-and-Formatting) on this topic. It currently covers the scripts added to both the server and client `package.json`

**Comment by gbowne1** [comment]
Feel free to use/open/comment in/on Discussions for anything that isn't a bug, issue, feature.. or even anything that is.. :100:
