### ISSUE TITLE
[Bug] CSS issue 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/TwitchBot#81]
Navigated to localhost:3000/leaderboard and a few other routes.

Looking in the browser console, you will see:

`Expected color but found ‘palette’.  Error in parsing value for ‘color’.  Declaration dropped.`

**Comment by jarmentor** [comment]
@gbowne1 -- I'm looking into this but I'm not seeing anything in my console; are there any additional steps to reproduce?

**Comment by gbowne1** [comment]
it doesn't seem to be all routes

**Comment by gbowne1** [comment]
@jarmentor 

Expected color but found ‘palette’.  Error in parsing value for ‘color’.  Declaration dropped. [localhost:3000:1:497](http://localhost:3000/)
Elements matching selector: .css-fpa1pu-MuiListItem-root
NodeList(6) [ li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root, li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root, li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root, li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root, li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root, li.MuiListItem-root.MuiListItem-gutters.MuiListItem-padding.css-fpa1pu-MuiListItem-root ]


Looks like there might be some issue with MUI ListItem.  It seems to happen with the drawer menu open.
