### ISSUE TITLE
Command card action alignment ( UI / MUI )

### ISSUE THREAD

**Issue by Sky-De** [gbowne1/TwitchBot#88]
**Describe the bug**
Command cards do not have the same size which causes card actions ( buttons ) in a row not to be aligned with other card actions

**To Reproduce**
1. Go to the main page
2. Click on sidebar
3. Click on commands

**Expected behavior**
Card actions should align themselves to the end of the command card component

**Screenshots**
Current UI :
![Screenshot 2024-05-14 031823](https://github.com/gbowne1/TwitchBot/assets/79264045/928a78cf-a3b9-4416-b498-be8a566120ef)

Excepted UI :
![Screenshot 2024-05-14 040608](https://github.com/gbowne1/TwitchBot/assets/79264045/b817ed31-7b5b-4e0d-9031-d9fb322fe05f)

[ x ] I will fix this issue and create a PR

**Comment by Sky-De** [comment]
@gbowne1 Hi assign this to me, I have already completed this task. I will wait for your assignment and then create a pull request, thanks , skyDe

**Comment by gbowne1** [comment]
@Sky-De 

Ok.
