### ISSUE TITLE
Setting page UI enhancement and responsiveness ( UI / MUI )

### ISSUE THREAD

**Issue by Sky-De** [gbowne1/TwitchBot#89]
**Describe the bug**
Currently settings page is not aligned with material design principles

**To Reproduce**
1. Go to the main page
2. Click on sidebar
3. Click on the setting

**Expected behavior**
The UI of this page should be clean and ordered for better UI / UX, also it should be responsive

**Screenshots**
Current UI Desktop :
![chrome-capture-2024-4-14](https://github.com/gbowne1/TwitchBot/assets/79264045/8bb36116-68c8-4c47-b686-bf28aa28583a)

Current UI Mobile :
![chrome-capture-2024-4-14 (1)](https://github.com/gbowne1/TwitchBot/assets/79264045/bbc3c6f2-cf02-43b0-a11e-3b9e929c5736)

[ x ] I will fix this issue and create a PR

**Comment by Sky-De** [comment]
@gbowne1 assign this to me please, I will fix this issue tomorrow morning and  you will receive PR related to this issue, thanks, skyDe

**Comment by gbowne1** [comment]
@Sky-De Ok. Thank you.
